# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Bio"
  url = "#about"
  weight = 5

[[main]]
  name = "Research"
  url = "#projects"
  weight = 10

[[main]]
name = "Publications"
  url = "#publications"
  weight = 20

[[main]]
  name = "Teaching"
  url = "#teaching"
  weight = 30
  
  [[main]]
  name = "Teaching"
  url = "#teaching"
  weight = 33
  
   [[main]]
  name = "Diplomacy"
  url = "#diplomatic"
  weight = 40
  


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
  name = "CV"
  url = "https://leidenuniv1-my.sharepoint.com/:b:/g/personal/davilagordillodl_vuw_leidenuniv_nl/IQC67ii1UYOZSYjtC04oci5fAan001h9JdqwWlTB2kP4vsE?e=tNsZLO"
  weight = 50
